# Generated by Django 4.2.1 on 2023-05-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='images')),
                ('description', models.TextField()),
                ('photo2', models.ImageField(upload_to='images')),
                ('photo3', models.ImageField(upload_to='images')),
                ('photo4', models.ImageField(upload_to='images')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
